[tool.poetry]
name = "yangpt_app"
version = "0.1.0"
description = ""
authors = ["l.gyeongmin"]
readme = "README.md"
packages = [{include = "yangpt_app"}]

[tool.poetry.dependencies]
python = "3.11.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
