# Generated by Django 4.2 on 2023-05-17 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yangpt_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='user_id',
            new_name='user',
        ),
    ]
